// Store specifications checked on 2026-09-30.
const APPLE_SCREENSHOTS =
  "https://developer.apple.com/help/app-store-connect/reference/app-information/screenshot-specifications/";
const PLAY_SCREENSHOTS =
  "https://support.google.com/googleplay/android-developer/answer/9866151?hl=en";
export const additionalStoreProfiles = [
  {
    id: "apple-iphone63-portrait",
    name: "App Store · iPhone · 6.3-inch · Portrait",
    store: "apple",
    category: "phone",
    width: 1206,
    height: 2622,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-iphone63-landscape",
    name: "App Store · iPhone · 6.3-inch · Landscape",
    store: "apple",
    category: "phone",
    width: 2622,
    height: 1206,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-iphone61-portrait",
    name: "App Store · iPhone · 6.1-inch · Portrait",
    store: "apple",
    category: "phone",
    width: 1170,
    height: 2532,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-iphone61-landscape",
    name: "App Store · iPhone · 6.1-inch · Landscape",
    store: "apple",
    category: "phone",
    width: 2532,
    height: 1170,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-iphone55-portrait",
    name: "App Store · iPhone · 5.5-inch · Portrait",
    store: "apple",
    category: "phone",
    width: 1242,
    height: 2208,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-iphone55-landscape",
    name: "App Store · iPhone · 5.5-inch · Landscape",
    store: "apple",
    category: "phone",
    width: 2208,
    height: 1242,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-iphone47-portrait",
    name: "App Store · iPhone · 4.7-inch · Portrait",
    store: "apple",
    category: "phone",
    width: 750,
    height: 1334,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-iphone47-landscape",
    name: "App Store · iPhone · 4.7-inch · Landscape",
    store: "apple",
    category: "phone",
    width: 1334,
    height: 750,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-iphone4-portrait",
    name: "App Store · iPhone · 4-inch · Portrait",
    store: "apple",
    category: "phone",
    width: 640,
    height: 1136,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-iphone4-landscape",
    name: "App Store · iPhone · 4-inch · Landscape",
    store: "apple",
    category: "phone",
    width: 1136,
    height: 640,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-iphone35-portrait",
    name: "App Store · iPhone · 3.5-inch · Portrait",
    store: "apple",
    category: "phone",
    width: 640,
    height: 960,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-iphone35-landscape",
    name: "App Store · iPhone · 3.5-inch · Landscape",
    store: "apple",
    category: "phone",
    width: 960,
    height: 640,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-ipad129-portrait",
    name: "App Store · iPad · 12.9-inch · Portrait",
    store: "apple",
    category: "tablet",
    width: 2048,
    height: 2732,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-ipad129-landscape",
    name: "App Store · iPad · 12.9-inch · Landscape",
    store: "apple",
    category: "tablet",
    width: 2732,
    height: 2048,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-ipad105-portrait",
    name: "App Store · iPad · 10.5-inch · Portrait",
    store: "apple",
    category: "tablet",
    width: 1668,
    height: 2224,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-ipad105-landscape",
    name: "App Store · iPad · 10.5-inch · Landscape",
    store: "apple",
    category: "tablet",
    width: 2224,
    height: 1668,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-ipad97-portrait",
    name: "App Store · iPad · 9.7-inch · Portrait",
    store: "apple",
    category: "tablet",
    width: 1536,
    height: 2048,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "apple-ipad97-landscape",
    name: "App Store · iPad · 9.7-inch · Landscape",
    store: "apple",
    category: "tablet",
    width: 2048,
    height: 1536,
    maxCount: 10,
    note: "Optional device slot; larger screenshots can be scaled by App Store Connect.",
    source: APPLE_SCREENSHOTS,
  },
  {
    id: "play-tablet7-8k-portrait",
    name: "Google Play · Tablet · 7-inch · 8K · Portrait",
    store: "google",
    category: "tablet",
    width: 4320,
    height: 7680,
    maxCount: 8,
    note: "Large-screen screenshot: 16:9 or 9:16, up to 7680 pixels.",
    source: PLAY_SCREENSHOTS,
  },
  {
    id: "play-tablet7-8k-landscape",
    name: "Google Play · Tablet · 7-inch · 8K · Landscape",
    store: "google",
    category: "tablet",
    width: 7680,
    height: 4320,
    maxCount: 8,
    note: "Large-screen screenshot: 16:9 or 9:16, up to 7680 pixels.",
    source: PLAY_SCREENSHOTS,
  },
  {
    id: "play-tablet10-8k-portrait",
    name: "Google Play · Tablet · 10-inch · 8K · Portrait",
    store: "google",
    category: "tablet",
    width: 4320,
    height: 7680,
    maxCount: 8,
    note: "Large-screen screenshot: 16:9 or 9:16, up to 7680 pixels.",
    source: PLAY_SCREENSHOTS,
  },
  {
    id: "play-tablet10-8k-landscape",
    name: "Google Play · Tablet · 10-inch · 8K · Landscape",
    store: "google",
    category: "tablet",
    width: 7680,
    height: 4320,
    maxCount: 8,
    note: "Large-screen screenshot: 16:9 or 9:16, up to 7680 pixels.",
    source: PLAY_SCREENSHOTS,
  },
  {
    id: "play-chromebook-8k-landscape",
    name: "Google Play · Chromebook · 8K · Landscape",
    store: "google",
    category: "desktop",
    width: 7680,
    height: 4320,
    maxCount: 8,
    note: "Large-screen screenshot: 16:9 or 9:16, up to 7680 pixels.",
    source: PLAY_SCREENSHOTS,
  },
] as const;
export const additionalStoreSlots = [
  {
    id: "apple-iphone63",
    name: "iPhone · 6.3-inch",
    store: "apple",
    category: "phone",
    profiles: {
      portrait: "apple-iphone63-portrait",
      landscape: "apple-iphone63-landscape",
    },
  },
  {
    id: "apple-iphone61",
    name: "iPhone · 6.1-inch",
    store: "apple",
    category: "phone",
    profiles: {
      portrait: "apple-iphone61-portrait",
      landscape: "apple-iphone61-landscape",
    },
  },
  {
    id: "apple-iphone55",
    name: "iPhone · 5.5-inch",
    store: "apple",
    category: "phone",
    profiles: {
      portrait: "apple-iphone55-portrait",
      landscape: "apple-iphone55-landscape",
    },
  },
  {
    id: "apple-iphone47",
    name: "iPhone · 4.7-inch",
    store: "apple",
    category: "phone",
    profiles: {
      portrait: "apple-iphone47-portrait",
      landscape: "apple-iphone47-landscape",
    },
  },
  {
    id: "apple-iphone4",
    name: "iPhone · 4-inch",
    store: "apple",
    category: "phone",
    profiles: {
      portrait: "apple-iphone4-portrait",
      landscape: "apple-iphone4-landscape",
    },
  },
  {
    id: "apple-iphone35",
    name: "iPhone · 3.5-inch",
    store: "apple",
    category: "phone",
    profiles: {
      portrait: "apple-iphone35-portrait",
      landscape: "apple-iphone35-landscape",
    },
  },
  {
    id: "apple-ipad129",
    name: "iPad · 12.9-inch",
    store: "apple",
    category: "tablet",
    profiles: {
      portrait: "apple-ipad129-portrait",
      landscape: "apple-ipad129-landscape",
    },
  },
  {
    id: "apple-ipad105",
    name: "iPad · 10.5-inch",
    store: "apple",
    category: "tablet",
    profiles: {
      portrait: "apple-ipad105-portrait",
      landscape: "apple-ipad105-landscape",
    },
  },
  {
    id: "apple-ipad97",
    name: "iPad · 9.7-inch",
    store: "apple",
    category: "tablet",
    profiles: {
      portrait: "apple-ipad97-portrait",
      landscape: "apple-ipad97-landscape",
    },
  },
  {
    id: "play-tablet7-8k",
    name: "Tablet · 7-inch · 8K",
    store: "google",
    category: "tablet",
    profiles: {
      portrait: "play-tablet7-8k-portrait",
      landscape: "play-tablet7-8k-landscape",
    },
  },
  {
    id: "play-tablet10-8k",
    name: "Tablet · 10-inch · 8K",
    store: "google",
    category: "tablet",
    profiles: {
      portrait: "play-tablet10-8k-portrait",
      landscape: "play-tablet10-8k-landscape",
    },
  },
  {
    id: "play-chromebook-8k",
    name: "Chromebook · 8K",
    store: "google",
    category: "desktop",
    profiles: { landscape: "play-chromebook-8k-landscape" },
  },
] as const;
export const appleFrameVariants: Record<
  string,
  { ratio: number; hardware: "island" | "notch" | "home" | "tablet" }
> = {
  "apple-iphone63": { ratio: 2622 / 1206, hardware: "island" },
  "apple-iphone61": { ratio: 2532 / 1170, hardware: "notch" },
  "apple-iphone55": { ratio: 2208 / 1242, hardware: "home" },
  "apple-iphone47": { ratio: 1334 / 750, hardware: "home" },
  "apple-iphone4": { ratio: 1136 / 640, hardware: "home" },
  "apple-iphone35": { ratio: 960 / 640, hardware: "home" },
  "apple-ipad129": { ratio: 2732 / 2048, hardware: "home" },
  "apple-ipad105": { ratio: 2224 / 1668, hardware: "home" },
  "apple-ipad97": { ratio: 2048 / 1536, hardware: "home" },
};
