import type { Template } from "./templates";
import { defineTemplate } from "./showcase-templates";
import { panoramaStyles } from "./panorama";

/** Seasonal artwork remains available year-round; every color stays editable. */
export const halloweenTemplates: readonly Template[] = [
  defineTemplate(
    {
      id: "jack-o-lantern",
      name: "Jack O’ Lantern",
      category: "Bold",
      appearance: "colorful",
      composition: "right-low",
      surfaceLabel: "Pumpkin patch",
      keywords: ["halloween", "october", "pumpkin", "orange", "autumn", "warm"],
      description: "A pumpkin patch for your next big launch.",
      note: "Carved pumpkins and warm orange shapes frame a device tilted toward the lower right, with a headline above and supporting text on the left.",
    },
    ["#F8E7CF", "#D97736", "#3D281F", "#94512E"],
    { rotation: -8, size: 116 },
  ),
  defineTemplate(
    {
      id: "cobweb",
      name: "Cobweb",
      category: "Editorial",
      appearance: "dark",
      composition: "left-high",
      surfaceLabel: "Cobweb corners",
      keywords: ["halloween", "october", "spider", "web", "charcoal", "gothic"],
      titleFont: "Fraunces",
      titleWeight: "600",
      description: "Fine threads. A quietly spooky frame.",
      note: "Silver cobwebs and small hanging spiders surround a raised device. A serif headline anchors the lower right.",
    },
    ["#202129", "#31333F", "#F3EDE1", "#B7B0C8"],
    { rotation: 5, size: 112 },
  ),
  defineTemplate(
    {
      id: "boo",
      name: "Boo",
      category: "Minimal",
      appearance: "light",
      composition: "right-high",
      surfaceLabel: "Friendly ghosts",
      keywords: [
        "halloween",
        "october",
        "ghost",
        "lavender",
        "cute",
        "playful",
      ],
      description: "A friendly little fright, in soft lavender.",
      note: "Paper-colored ghosts float around a raised device on a lavender backdrop, with a generous headline below.",
    },
    ["#F2ECF5", "#D6C7E2", "#3E304B", "#9375AA"],
    { rotation: -5, size: 116 },
  ),
  defineTemplate(
    {
      id: "witching-hour",
      name: "Witching Hour",
      category: "Editorial",
      appearance: "dark",
      composition: "diagonal-center",
      surfaceLabel: "Witch hat & stars",
      keywords: [
        "halloween",
        "october",
        "witch",
        "stars",
        "plum",
        "gold",
        "magic",
      ],
      titleFont: "Fraunces",
      titleWeight: "600",
      description: "Plum, starlight, and a little magic.",
      note: "A tilted device rests inside a celestial circle, with a witch hat and gold stars. Serif captions sit above and below.",
    },
    ["#302237", "#594060", "#F9EBDC", "#D4B16C"],
    { rotation: 14, size: 116 },
  ),
  defineTemplate(
    {
      id: "candy-club",
      name: "Candy Club",
      category: "Bold",
      appearance: "colorful",
      composition: "raised-center",
      surfaceLabel: "Wrapped candy",
      keywords: [
        "halloween",
        "october",
        "candy",
        "pink",
        "orange",
        "sweet",
        "playful",
      ],
      description: "All treats. A sweeter way to show your app.",
      note: "Wrapped sweets and candy-colored ribbons border a centered device, with the headline and supporting text below.",
    },
    ["#F8DAB1", "#E8AAB6", "#492D40", "#AC729F"],
    { rotation: 0, size: 114 },
  ),
  {
    ...defineTemplate(
      {
        id: "moonlight",
        name: "Moonlight",
        category: "Editorial",
        appearance: "dark",
        surfaceLabel: "Moonlit night · 2 slides",
        keywords: [
          "halloween",
          "october",
          "moon",
          "bats",
          "night",
          "navy",
          "forest",
        ],
        titleFont: "Fraunces",
        titleWeight: "600",
        description: "One moonlit night. A story across two slides.",
        note: "A large moon, flying bats, and rolling night hills connect two slides around one shared device. Each slide keeps its own text.",
      },
      ["#192236", "#30405A", "#F5EBD8", "#C6B7A6"],
    ),
    style: panoramaStyles.moonlight,
  },
].map((template) => ({
  ...template,
  deviceInset: template.id === "witching-hour" ? 0.03 : 0.09,
}));
