import type { Template } from "./templates";
import { defineTemplate } from "./showcase-templates";

/** Timeless seasonal designs: no fixed year, date, or baked-in caption. */
export const holidayTemplates: readonly Template[] = [
  defineTemplate(
    {
      id: "evergreen",
      name: "Evergreen",
      category: "Editorial",
      appearance: "dark",
      composition: "right-low",
      surfaceLabel: "Pine & ornaments",
      titleFont: "Fraunces",
      titleWeight: "600",
      keywords: ["christmas", "december", "pine", "ornaments", "green", "gold"],
      description: "Deep forest green. A little Christmas gold.",
      note: "Pine branches and hanging ornaments frame a tilted device, with generous space for a serif headline above.",
    },
    ["#173C32", "#2C5745", "#FAF0D8", "#D4B578"],
    { rotation: -7, size: 116 },
  ),
  defineTemplate(
    {
      id: "snowfall",
      name: "Snowfall",
      category: "Minimal",
      appearance: "light",
      composition: "left-high",
      surfaceLabel: "Paper snowflakes",
      keywords: [
        "christmas",
        "december",
        "winter",
        "snow",
        "snowflakes",
        "blue",
      ],
      description: "Fresh snow. A quieter kind of Christmas.",
      note: "Delicate snowflakes and soft snowdrifts surround a raised device, balanced by a clear headline below.",
    },
    ["#EDF4F5", "#CCDFE4", "#284C5B", "#739AAA"],
    { rotation: 5, size: 112 },
  ),
  defineTemplate(
    {
      id: "gift-wrap",
      name: "Gift Wrap",
      category: "Bold",
      appearance: "colorful",
      composition: "diagonal-center",
      surfaceLabel: "Ribbon & plaid",
      keywords: ["christmas", "december", "gift", "ribbon", "plaid", "red"],
      description: "Your app, wrapped for the holidays.",
      note: "Cranberry checks and a generous ribbon bow wrap around a diagonal device. Captions sit above and below.",
    },
    ["#F6E8D7", "#DBBDB1", "#752D36", "#AB4350"],
    { rotation: 14, size: 116 },
  ),
  defineTemplate(
    {
      id: "gingerbread",
      name: "Gingerbread",
      category: "Bold",
      appearance: "colorful",
      composition: "right-high",
      surfaceLabel: "Iced gingerbread",
      keywords: [
        "christmas",
        "december",
        "cookies",
        "gingerbread",
        "cinnamon",
        "cream",
      ],
      description: "A warm welcome, with icing on top.",
      note: "Iced cookie houses, trees, and stars surround a raised device. A warm cinnamon palette leaves the lower headline in focus.",
    },
    ["#F8EBDD", "#E5C4A2", "#59382A", "#A76A45"],
    { rotation: -5, size: 114 },
  ),
  defineTemplate(
    {
      id: "midnight",
      name: "Midnight",
      category: "Editorial",
      appearance: "dark",
      composition: "diagonal-center",
      surfaceLabel: "Art deco celebration",
      titleFont: "Fraunces",
      titleWeight: "600",
      keywords: [
        "new year",
        "january",
        "celebration",
        "art deco",
        "black",
        "gold",
      ],
      description: "A golden entrance to the new year.",
      note: "Fine geometric fans and gold stars frame a diagonal device on charcoal, with elegant serif captions above and below.",
    },
    ["#242629", "#373B3F", "#F8EBD4", "#C5A66B"],
    { rotation: -12, size: 116 },
  ),
  defineTemplate(
    {
      id: "firework",
      name: "Firework",
      category: "Bold",
      appearance: "dark",
      composition: "left-low",
      surfaceLabel: "Fireworks at night",
      keywords: [
        "new year",
        "january",
        "celebration",
        "fireworks",
        "navy",
        "copper",
      ],
      description: "Start the year with a spark.",
      note: "Copper fireworks burst around a low device against a deep navy sky, leaving open space for your message.",
    },
    ["#202B43", "#34476A", "#FBEBD9", "#DF9673"],
    { rotation: 6, size: 118 },
  ),
  defineTemplate(
    {
      id: "countdown",
      name: "Countdown",
      category: "Bold",
      appearance: "colorful",
      composition: "raised-center",
      surfaceLabel: "Clock & streamers",
      keywords: [
        "new year",
        "january",
        "celebration",
        "clock",
        "streamers",
        "pink",
      ],
      description: "A little anticipation. A brand-new chapter.",
      note: "A celebration clock, curled streamers, and scattered confetti surround a centered device, with a bold headline below.",
    },
    ["#F9E8DC", "#E6BDB9", "#653341", "#AD5368"],
    { rotation: 0, size: 116 },
  ),
  defineTemplate(
    {
      id: "first-light",
      name: "First Light",
      category: "Minimal",
      appearance: "light",
      composition: "left-middle",
      surfaceLabel: "New year sunrise",
      keywords: [
        "new year",
        "january",
        "sunrise",
        "sage",
        "fresh start",
        "cream",
      ],
      description: "A fresh start, in softer light.",
      note: "A rising sun and fine rays trace an arch behind the device. Soft sage and cream keep the new-year message calm and clear.",
    },
    ["#F4F0DF", "#D9DFC5", "#374B3B", "#889467"],
    { rotation: -4, size: 112 },
  ),
].map((template) => ({ ...template, deviceInset: 0.09 }));
