// Additional platform slots, checked against the linked store specifications on 2026-09-09.
export const specialProfiles = [
  {
    id: "apple-tv-hd",
    name: "App Store · Apple TV · HD",
    store: "apple",
    category: "desktop",
    width: 1920,
    height: 1080,
    maxCount: 10,
    note: "Use captures from the tvOS app.",
    source:
      "https://developer.apple.com/help/app-store-connect/reference/app-information/screenshot-specifications/",
  },
  {
    id: "apple-tv-4k",
    name: "App Store · Apple TV · 4K",
    store: "apple",
    category: "desktop",
    width: 3840,
    height: 2160,
    maxCount: 10,
    note: "Use captures from the tvOS app.",
    source:
      "https://developer.apple.com/help/app-store-connect/reference/app-information/screenshot-specifications/",
  },
  {
    id: "apple-vision",
    name: "App Store · Apple Vision Pro",
    store: "apple",
    category: "desktop",
    width: 3840,
    height: 2160,
    maxCount: 10,
    note: "Use captures from the visionOS app.",
    source:
      "https://developer.apple.com/help/app-store-connect/reference/app-information/screenshot-specifications/",
  },
  {
    id: "apple-watch-422",
    name: "App Store · Apple Watch · 422 × 514",
    store: "apple",
    category: "phone",
    width: 422,
    height: 514,
    maxCount: 10,
    note: "Use the same Apple Watch screenshot size in every language.",
    source:
      "https://developer.apple.com/help/app-store-connect/reference/app-information/screenshot-specifications/",
  },
  {
    id: "apple-watch-410",
    name: "App Store · Apple Watch · 410 × 502",
    store: "apple",
    category: "phone",
    width: 410,
    height: 502,
    maxCount: 10,
    note: "Use the same Apple Watch screenshot size in every language.",
    source:
      "https://developer.apple.com/help/app-store-connect/reference/app-information/screenshot-specifications/",
  },
  {
    id: "apple-watch-416",
    name: "App Store · Apple Watch · 416 × 496",
    store: "apple",
    category: "phone",
    width: 416,
    height: 496,
    maxCount: 10,
    note: "Use the same Apple Watch screenshot size in every language.",
    source:
      "https://developer.apple.com/help/app-store-connect/reference/app-information/screenshot-specifications/",
  },
  {
    id: "apple-watch-396",
    name: "App Store · Apple Watch · 396 × 484",
    store: "apple",
    category: "phone",
    width: 396,
    height: 484,
    maxCount: 10,
    note: "Use the same Apple Watch screenshot size in every language.",
    source:
      "https://developer.apple.com/help/app-store-connect/reference/app-information/screenshot-specifications/",
  },
  {
    id: "apple-watch-368",
    name: "App Store · Apple Watch · 368 × 448",
    store: "apple",
    category: "phone",
    width: 368,
    height: 448,
    maxCount: 10,
    note: "Use the same Apple Watch screenshot size in every language.",
    source:
      "https://developer.apple.com/help/app-store-connect/reference/app-information/screenshot-specifications/",
  },
  {
    id: "apple-watch-312",
    name: "App Store · Apple Watch · 312 × 390",
    store: "apple",
    category: "phone",
    width: 312,
    height: 390,
    maxCount: 10,
    note: "Use the same Apple Watch screenshot size in every language.",
    source:
      "https://developer.apple.com/help/app-store-connect/reference/app-information/screenshot-specifications/",
  },
  {
    id: "play-wear",
    name: "Google Play · Wear OS",
    store: "google",
    category: "phone",
    width: 384,
    height: 384,
    maxCount: 8,
    note: "Wear OS requires the app interface only: no device frame, extra text, graphics, or transparent masking.",
    source:
      "https://support.google.com/googleplay/android-developer/answer/9866151?hl=en",
    sourceOnly: true,
  },
  {
    id: "play-tv",
    name: "Google Play · Android TV screenshots",
    store: "google",
    category: "desktop",
    width: 1920,
    height: 1080,
    maxCount: 8,
    note: "Provide at least one Android TV screenshot and a separate Android TV banner.",
    source:
      "https://support.google.com/googleplay/android-developer/answer/9866151?hl=en",
  },
  {
    id: "play-xr",
    name: "Google Play · Android XR",
    store: "google",
    category: "desktop",
    width: 3840,
    height: 2400,
    maxCount: 8,
    note: "Android XR needs 4–8 screenshots, each up to 8 MB.",
    source:
      "https://support.google.com/googleplay/android-developer/answer/9866151?hl=en",
    maxBytes: 8000000,
  },
  {
    id: "play-auto-portrait",
    name: "Google Play · Automotive · Portrait",
    store: "google",
    category: "desktop",
    width: 800,
    height: 1280,
    maxCount: 8,
    note: "For Automotive screenshot sets, provide at least 2 portrait and 2 landscape captures using the generic system UI.",
    source:
      "https://support.google.com/googleplay/android-developer/answer/9866151?hl=en",
  },
  {
    id: "play-auto-landscape",
    name: "Google Play · Automotive · Landscape",
    store: "google",
    category: "desktop",
    width: 1024,
    height: 768,
    maxCount: 8,
    note: "For Automotive screenshot sets, provide at least 2 portrait and 2 landscape captures using the generic system UI.",
    source:
      "https://support.google.com/googleplay/android-developer/answer/9866151?hl=en",
  },
] as const;
